name: Component Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install deps
        run: |
          npm cache clean --force
          npm ci --prefer-offline --no-audit
      - name: Run tests
        run: npm test

